# items-jwt.http
### auth login

# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "u1002",
    "password": "changeit"
}

###
@authToken = {{login.response.body.access_token}}


### find all
GET http://localhost:3000/items
Authorization: Bearer {{authToken}}


### find all with static jwt
GET http://localhost:3000/items
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywidXNlcm5hbWUiOiJ1MTAwNiIsInJvbGUiOiJVU0VSIiwic3ViIjo3LCJpYXQiOjE3Mjc3MDU4NDV9.g9My7bo039yYoYP1tMg3TNPsy_PRUZpIgoEYvoMkDTU


### find all with invalid jwt
GET http://localhost:3000/items
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywidXNlcm5hbWUiOiJ1MTAwNiIsInJvbGUiOiJVU0VSIiwic3ViIjo3LCJpYXQiOjE3Mjc3MDE0NTh9.6nVoU3NazKVijuhNclLtm1nil8UAeflXjPHFIzm_MGs

### find all with wrong jwt format
GET http://localhost:3000/items
Authorization: Bearer WRONG

### approve
PATCH http://localhost:3000/items/1/approve
Authorization: Bearer {{authToken}}


###
### Admin Zone
###
# @name loginAdmin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "a1001",
    "password": "changeit"
}

###
@authTokenAdmin = {{loginAdmin.response.body.access_token}}

### find all
PATCH http://localhost:3000/items/1/approve
Authorization: Bearer {{authTokenAdmin}}


###
### Manager Zone
###
# @name loginManager
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "m1001",
    "password": "changeit"
}

###
@authTokenManager = {{loginManager.response.body.access_token}}

### Manager approve
PATCH http://localhost:3000/items/4/approve
Authorization: Bearer {{authTokenManager}}