# items.http
### create
POST http://localhost:3000/items
Content-Type: application/json

{
    "title": "Mouse",
    "amount": 10,
    "price": 5000,
    "contactMobileNo": "0891234567"
}

### find all
GET http://localhost:3000/items

### find one
GET http://localhost:3000/items/1

### update
PATCH http://localhost:3000/items/2
Content-Type: application/json

{
    "title": "Mouse wireless",
    "contactMobileNo": "0891234567"
}

### delete
DELETE http://localhost:3000/items/1

### find one by string
GET http://localhost:3000/items/A
