# users.http
### create
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "u1001",
    "password": "changeit",
    "role": "USER"
}

### create with description
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "u1007",
    "password": "changeit",
    "role": "USER",
    "description": "general user"
}

### create
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "u1002",
    "password": "changeit",
    "role": "USER"
}

### find  all
GET http://localhost:3000/users


###
### Admin Zone
###
### create
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "a1001",
    "password": "changeit",
    "role": "ADMIN"
}


###
### Manager Zone
###
### create
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "m1001",
    "password": "changeit",
    "role": "MANAGER"
}